# Generated by Django 4.2.7 on 2023-12-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0005_collector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='client_name',
            new_name='client_Id',
        ),
    ]
