# Generated by Django 4.2.7 on 2023-12-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0006_rename_client_name_loan_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='client_Id',
            new_name='client_id',
        ),
    ]
