# Generated by Django 4.2.7 on 2023-12-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0011_loan_loan_balance_alter_loan_checking_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='checking_no',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
