# Generated by Django 4.2.7 on 2023-12-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0014_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='hasActiveLoan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='checking_no',
            field=models.CharField(max_length=250),
        ),
    ]
