# Generated by Django 4.2.7 on 2023-12-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0015_loan_hasactiveloan_alter_loan_checking_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='hasActiveLoan',
            field=models.BooleanField(default=True),
        ),
    ]
