# Generated by Django 4.2.7 on 2023-12-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0016_alter_loan_hasactiveloan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='hasActiveLoan',
            new_name='has_active_loan',
        ),
    ]
