# Generated by Django 5.0 on 2023-12-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0018_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='password',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
